services:
  mongodb:
    image: mongo:7
    container_name: pact-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pactdb
    networks:
      - pact-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pact-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/pactdb
    networks:
      - pact-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pact-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pact-network

volumes:
  mongodb_data:

networks:
  pact-network:
    driver: bridge