services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pact-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - pact-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: pact-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pact-network


networks:
  pact-network:
    driver: bridge